package com.b4nkd.creditscore.equifax.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * ErrorResponseInner
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-08T10:55:31.099545300Z[Europe/London]")


public class ErrorResponseInner   {
  @JsonProperty("code")
  private String code = null;

  /**
   * Error type
   */
  public enum ErrorTypeEnum {
    CERR("CERR"),
    
    MERR("MERR");

    private String value;

    ErrorTypeEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ErrorTypeEnum fromValue(String text) {
      for (ErrorTypeEnum b : ErrorTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
  @JsonProperty("errorType")
  private ErrorTypeEnum errorType = null;

  @JsonProperty("message")
  private String message = null;

  public ErrorResponseInner code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Error code types\\:  CERR: Code Error Message Response   NARRATIVE CODES:   - 001: CUSTOMER NUMBER/SECURITY CODE INVALID (DIAL)   - 002: TELEPROCESSING TYPE CODE INVALID   - 003: CUSTOMER CODE INVALID   - 004: INPUT FORMAT CODE INVALID   - 005: OUTPUT FORMAT CODE INVALID   - 006: NUMBER OF MONTHS TO COUNT INQUIRIES INVALID (DIAL)   - 007: NUMBER OF MONTHS TO COUNT MAXIMUM DELINQUENCIES INV. (DIAL)   - 008: INPUT FORMAT INVALID   - 009: ADDITIONAL INPUT INVALID UNTIL DIAL COMPLETE   - 010: CUSTOMER NUMBER INVALID/DTEC ONLY (DIAL)   - 015: ACCOUNT SUSPENDED DUE TO NON-PAYMENT. CALL 800-685-6000 FOR RESOLUTION   - 00A: MULTIPLE CODE INVALID   - 00B: INPUT FORMAT INVALID   - 00C: FILE SELECTION CODE INVALID   - 00D: DIAL LINE DOES NOT END WITH A PERIOD   - 00E: INVALID PLAIN/TRADITIONAL LANGUAGE REQUEST CODE - FIXED INPUT   - 00F: INDUSTRY CODE INVALID FOR ACCESS CODE (DIAL-ACIS)   REQUEST CODES:   - 021: SEGMENT COUNT NOT EQUAL TO SEGMENTS IN   - 026: CUSTOMER NUMBER/SECURITY CODE INVALID (IDNT)   - 027: SEGMENT COUNT NON-NUMERIC   - 028: ECOA INQUIRY TYPE INVALID   - 029: TYPE OF PROCESSING CODE INVALID   - 032: INDUSTRY CODE INVALID FOR ACCESS CODE (IDNT-ACIS)   - 033: CUSTOMER NUMBER INVALID/DTEC ONLY (IDNT)   - 034: INVALID OPTIONAL FEATURE CODE   - 02A: NUMBER OF MONTHS TO COUNT INQUIRIES INVALID (IDNT)   - 02B: NUMBER OF MONTHS TO COUNT MAXIMUM DELINQ. INV. IDNT   - 02C: INVALID SEGMENT IDENTIFIER   - 02D: MINNESOTA FILES ARE BLOCKED   - 02E: CHARACTER NOT IN STANDARD CHARACTER SET   - 02F: INCOMPLETE IDNT SEGMENT   - 03A: IMPROPER DELIMITER ON ACRO INQUIRY   - 03B: CUSTOMER NUMBER IS EQUAL TO ‘IG’, ‘IL’ ‘IZ’ AND ‘ZB’ AND A PERMISSIBLE PURPOSE CODE IS NOT PRESENT   - 03C: REQUIRED FIELD IS MISSING ON “EU” SEGMENT   - 03D: MORE THAN ONE “EU” SEGMENT IS PRESENT ON IDNT   - 03E: CUSTOMER NUMBER IS NOT EQUAL TO A “ZB” AND “EU” IS PRESENT   - 03F: VERMONT FILES BLOCKED - CONTACT 1-800-685-5000 FOR REQUIRED CERTIFICATION   - 0E0: \\*\\*END USER NOT IDENTIFIED – CONTACT 1-800-685-5000 FOR INFORMATION\\*\\*   - 0EF: PERMISSIBLE PURPOSE CODE IS REQUIRED FOR THIS PRODUCT   - 0F1: PRODUCT NOT AVAILABLE TO INSURANCE INDUSTRY   The following refers to the first 42 bytes of the record:   - 101: INVALID CUSTOMER NUMBER   - 102: INVALID TELEPROCESSING TYPE   - 103: INVALID COMPANY CODE   - 104: INVALID INPUT/OUTPUT CODE   - 105: ACCOUNT SUSPENDED DUE TO NON-PAYMENT. CALL 800-685-6000 FOR RESOLUTION   - 1F1: LINE ONE DUPLICATE LINES   - 1F2: LINE ONE UNACCEPTABLE FOREIGN BUREAU LINE   - 1F3: LINE ONE INVALID LINE MNEMONIC   - 1F4: LINE ONE LONGER THAN 80 BYTES   Error codes used in the segment’s name portion:   - 201: INVALID LAST NAME   - 202: INVALID FIRST NAME   - 203: INVALID MIDDLE NAME   - 204: INVALID SUFFIX   - 205: INVALID SPOUSE NAME   - 2F1: LINE TWO DUPLICATE LINES   - 2F2: LINE TWO UNACCEPTABLE FOREIGN BUREAU LINE   - 2F3: LINE TWO INVALID LINE MNEMONIC   - 2F4: LINE TWO LONGER THAN 80 BYTES   Inquiry Search Information Error Codes:   - 031: INVALID PHONE NUMBER   - 401: INVALID SUBJECT SOCIAL SECURITY NUMBER   - 403: INVALID SUBJECT AGE   - 404: INVALID SUBJECT SEX   - 405: INVALID SPOUSE BIRTH DATE   - 406: INVALID SPOUSE SOCIAL SECURITY NUMBER   - 407: INVALID NUMBER OF DEPENDENTS   - 408: INVALID MARITAL STATUS   - 4F1: LINE FOUR DUPLICATE LINES   - 4F2: LINE FOUR UNACCEPTABLE FOREIGN BUREAU LINE   - 4F3: LINE FOUR INVALID LINE MNEMONIC   - 4F4: LINE FOUR LONGER THAN 80 BYTES   - 022: MAXIMUM NUMBER OF “AD” SEGMENTS EXCEEDED   - 025: AD SEGMENT DOES NOT FOLLOW IDNT SEGMENT       The codes to follow refer to the first AD Segment:   - 301: INVALID STREET NUMBER   - 302: INVALID STREET NAME   - 303: INVALID STREET TYPE   - 304: INVALID CITY NAME   - 305: INVALID STATE CODE   - 306: INVALID ZIP CODE   - 307: INVALID FILE SINCE   - 308: INVALID R-O-B CODE   - 3F1: LINE THREE DUPLICATE LINES   - 3F2: LINE THREE UNACCEPTABLE FOREIGN BUREAU LINE   - 3F3: LINE THREE INVALID LINE MNEMONIC   - 3F4: LINE THREE LONGER THAN 80 BYTES   These next codes refer to the second AD Segment:   - 501: INVALID FORMER ADDRESS STREET NUMBER   - 503: INVALID FORMER ADDRESS STREET TYPE   - 504: INVALID FORMER ADDRESS CITY NAME   - 505: INVALID FORMER ADDRESS STATE CODE   - 506: INVALID FORMER ADDRESS ZIP CODE   - 507: INVALID FORMER ADDRESS DATE SINCE   - 508: INVALID FORMER ADDRESS R-O-B CODE   - 5F1: LINE FIVE DUPLICATE LINES   - 5F2: LINE FIVE UNACCEPTABLE FOREIGN BUREAU LINE   - 5F3: LINE FIVE INVALID LINE MNEMONIC   - 5F4: LINE FIVE LONGER THAN 80 BYTES   - 6F1: LINE SIX DUPLICATE LINES   - 6F2: LINE SIX UNACCEPTABLE FOREIGN BUREAU LINE   - 6F3: LINE SIX INVALID LINE MNEMONIC   - 6F4: LINE SIX LONGER THAN 80 BYTES      JA Segment Error Conditions:   - 032: MORE THAN ONE JA SEGMENT WAS FOUND     ES Segment Error Conditions:   - 023: MORE THAN ONE ES SEGMENT ENCOUNTERED   - 024: ES SEGMENT DOES NOT FOLLOW AD SEGMENT   - 030: EMPLOYER NAME IS LONGER THAN 35 BYTES     EU Segment Error Conditions:   - 03B: CUSTOMER NUMBER IS EQUAL TO ‘IG’, ‘IL’, ‘IZ’ AND ‘ZB’ AND A PERMISSIBLE PURPOSE CODE IS NOT PRESENT   - 03C: TEXT OR PERMISSIBLE PURPOSE CODE NOT ON “EU” SEG   - 03D: MORE THAN ONE “EU” SEGMENT IS PRESENT ON IDNT   - 03E: CUSTOMER NUMBER IS NOT EQUAL TO A “ZB” AND “EU” IS PRESENT   - 0E0: \\*\\* END USER NOT IDENTIFIED – CONTACT 1-800-685-5000 FOR INFORMATION \\*\\*   - 0EF: PERMISSIBLE PURPOSE CODE IS REQUIRED FOR THIS PRODUCT   - 0F0: INVALID FCRA PERMISSIBLE PURPOSE OR GLB EXCEPTION FOR PRODUCT REQUESTED   - 0F1: PRODUCT NOT AVAILABLE TO INSURANCE INDUSTRY   - 602: LINE 6 FIELD 2 PROBLEM (DIAL SEGMENT = LINE 1)   - 702: INCORRECT PERMISSIBLE PURPOSE CODE         PC Segment Error Conditions:   - 0E2: INVALID PC CODE   - 0E3: MULTIPLE PC CODES NOT ALLOWED   - 0E4: ZIP CODE IS A REQUIRED FIELD   - 0E5: PC SEGMENT REQUIRED WITH PI   - 0E6: ONLY ONE PC SEGMENT ALLOWED   - 0E9: MAXIMUM ALLOWANCE OF PC CODES EXCEEDED   - 0EA: RISKWISE AUTHORIZATION REQUIRED – CONTACT YOUR SALES REP   - 0EB: FRAUD ADVISOR NOT AVAILABLE – CONTACT YOUR SALES REP   - 0EC: ID ADVISOR NOT AVAILABLE – CONTACT YOUR SALES REP   - 0ED: ID ADVISOR PLUS NOT AVAILABLE – CONTACT YOUR SALES REP   - 0EE: MARKETMAX NOT AVAILABLE – CONTACT YOUR SALES REP      PI Segment Error Conditions:   - 0E5: PC SEGMENT REQUIRED WITH PI   - 0E7: ONLY ONE PI SEGMENT ALLOWED   - 0E8: INVALID OR INCOMPLETE DATA ON PI SEGMENT       Processing Error Codes (Processing Error Codes apply to the Fixed Inquiry Format.):   - 002: NO RECORD FOUND - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 003: ERROR IN MASTER RECORD - CONTACT EQUIFAX AUTOMATED DELIVERY SYSTEMS   - 006: SPOUSE NAME REQUIRED FOR JOINT FILE ACCESS   - 008: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 009: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 00A: YOUR TRANSACTION WAS NOT COMPLETED - ERROR HAS OCCURRED IN SEARCHING FILE   - 014: RE-ENTER YOUR ENTIRE TRANSACTION - FILE HAS BEEN CHANGED SINCE YOU INQUIRED   - 015: CONTACT EQUIFAX - AUTOMATED DELIVERY SYSTEMS   - 01B: YOUR NM LINE IS INVALID   - 01C: YOUR ADDRESS LINE IS INVALID   - 01D: CURRENT AND FORMER ADDRESS BOTH OUT OF AREA   - 021: ERROR IN PREPARING YOUR FORM - RE-ORDER FORM - BILLING AND MAINTENANCE IS OK   - 02B: CA - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02C: FA - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02D: F2 - CITY OR STATE MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02E: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 03A: NO ADDITIONAL BILLING ENTRIES ALLOWED WITH BILL - NO   - 03E: YOUR REPLY IS INVALID SINCE IT HAS ALREADY BEEN ENTERED ON THIS TRANSACTION   - 040: NOT AUTHORIZED TO RECEIVE THIS PRODUCT   - 045: PROGRAM ERROR - PRINT TOTAL TRANSACTION AND NOTIFY AUTOMATION DIVISION (CONTACT BUREAU)   - 046: ADDRESS - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 04A: INVALID SECURITY CODE - USE YOUR CORRECT CODE   - 06E: INVALID REQUEST   - 076: CONTACT BUREAU SUPERVISOR - FILE EXCEEDS MAXIMUM LENGTH   - 077: CANCELED CUSTOMER NUMBER - CONTACT EQUIFAX SALES DEPARTMENT   - 078: SECURITY VIOLATION - UNAUTHORIZED TRANSACTION TYPE   - 079: UNABLE TO BUILD SUMMARY OUTPUT FOR THIS RECORD   - 07A: UNABLE TO BUILD TOTALVIEW FULL-FILE FIXED OUTPUT FOR THIS RECORD   - 07B: UNABLE TO BUILD PRINT IMAGE OUTPUT FOR THIS RECORD   - 07C: INSUFFICIENT INFORMATION FOR FILE SEARCH – ADDITIONAL DATA IS NEEDED   - 0A3: SOCIAL SECURITY NUMBER IS REQUIRED TO ACCESS PUERTO RICO FILES   - 0A4: NO RECORD SUBJECT (JOINT FILE ACCESS) - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 0A5: NO RECORD SPOUSE (JOINT FILE ACCESS) - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 0A7: COMBINED FILE IS TOO LARGE FOR PROCESSING. PLEASE RE-SUBMIT USING ONLY CANADIAN ADDRESS   - 0A8: NO CANADIAN ADDRESS IN THE INQUIRY.   - 0A9: CANADIAN FILE NOT AVAILABLE IN ACROFILE PLUS FORMAT   - 0C6: SOCIAL SECURITY NUMBER REQUIRED ON INPUT WHEN USING MILITARY ADDRESS   - 0E1: VERMONT FILES BLOCKED - CONTACT 1-800-685-5000 FOR REQUIRED CERTIFICATION   - 0F0: INVALID FCRA PERMISSIBLE PURPOSE OR GLB EXCEPTION FOR PRODUCT REQUESTED   - 0F9: CURRENT ADDRESS ON FILE IS MINNESOTA - FILE BLOCKED   - 4F5: INVALID ACCOUNT NUMBER   MERR: Model Data Response Error  NARRATIVE CODES:   - M00010: Model Segment Invalid   - M20010: Invalid Model Segment Input Data.   - M20020: Message will be one of the following five:   - M20030:   - M20040: Invalid Alpha-nn   - M20050: Invalid Numeric-nn   - M20060: Invalid Alpha/Numeric-nn   - M20070: Invalid Date-nn   - M20080: Invalid Length-nn   - M20100: Where “nn” and the 4th and 5th digits of the error number indicate which “MD” field that is error   - M20400: Member Number is not Authorized for Model Delivery   - M20500: “MD” Segment contains Invalid Number of Input Fields   - M20600: Error in Report ID not using a prescreen   - M20700: Error in Report ID multi model Not G,P, or DDT09   - M20800: Error conflicting report Ids in the MAT table set up 
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Error code types\\:  CERR: Code Error Message Response   NARRATIVE CODES:   - 001: CUSTOMER NUMBER/SECURITY CODE INVALID (DIAL)   - 002: TELEPROCESSING TYPE CODE INVALID   - 003: CUSTOMER CODE INVALID   - 004: INPUT FORMAT CODE INVALID   - 005: OUTPUT FORMAT CODE INVALID   - 006: NUMBER OF MONTHS TO COUNT INQUIRIES INVALID (DIAL)   - 007: NUMBER OF MONTHS TO COUNT MAXIMUM DELINQUENCIES INV. (DIAL)   - 008: INPUT FORMAT INVALID   - 009: ADDITIONAL INPUT INVALID UNTIL DIAL COMPLETE   - 010: CUSTOMER NUMBER INVALID/DTEC ONLY (DIAL)   - 015: ACCOUNT SUSPENDED DUE TO NON-PAYMENT. CALL 800-685-6000 FOR RESOLUTION   - 00A: MULTIPLE CODE INVALID   - 00B: INPUT FORMAT INVALID   - 00C: FILE SELECTION CODE INVALID   - 00D: DIAL LINE DOES NOT END WITH A PERIOD   - 00E: INVALID PLAIN/TRADITIONAL LANGUAGE REQUEST CODE - FIXED INPUT   - 00F: INDUSTRY CODE INVALID FOR ACCESS CODE (DIAL-ACIS)   REQUEST CODES:   - 021: SEGMENT COUNT NOT EQUAL TO SEGMENTS IN   - 026: CUSTOMER NUMBER/SECURITY CODE INVALID (IDNT)   - 027: SEGMENT COUNT NON-NUMERIC   - 028: ECOA INQUIRY TYPE INVALID   - 029: TYPE OF PROCESSING CODE INVALID   - 032: INDUSTRY CODE INVALID FOR ACCESS CODE (IDNT-ACIS)   - 033: CUSTOMER NUMBER INVALID/DTEC ONLY (IDNT)   - 034: INVALID OPTIONAL FEATURE CODE   - 02A: NUMBER OF MONTHS TO COUNT INQUIRIES INVALID (IDNT)   - 02B: NUMBER OF MONTHS TO COUNT MAXIMUM DELINQ. INV. IDNT   - 02C: INVALID SEGMENT IDENTIFIER   - 02D: MINNESOTA FILES ARE BLOCKED   - 02E: CHARACTER NOT IN STANDARD CHARACTER SET   - 02F: INCOMPLETE IDNT SEGMENT   - 03A: IMPROPER DELIMITER ON ACRO INQUIRY   - 03B: CUSTOMER NUMBER IS EQUAL TO ‘IG’, ‘IL’ ‘IZ’ AND ‘ZB’ AND A PERMISSIBLE PURPOSE CODE IS NOT PRESENT   - 03C: REQUIRED FIELD IS MISSING ON “EU” SEGMENT   - 03D: MORE THAN ONE “EU” SEGMENT IS PRESENT ON IDNT   - 03E: CUSTOMER NUMBER IS NOT EQUAL TO A “ZB” AND “EU” IS PRESENT   - 03F: VERMONT FILES BLOCKED - CONTACT 1-800-685-5000 FOR REQUIRED CERTIFICATION   - 0E0: \\*\\*END USER NOT IDENTIFIED – CONTACT 1-800-685-5000 FOR INFORMATION\\*\\*   - 0EF: PERMISSIBLE PURPOSE CODE IS REQUIRED FOR THIS PRODUCT   - 0F1: PRODUCT NOT AVAILABLE TO INSURANCE INDUSTRY   The following refers to the first 42 bytes of the record:   - 101: INVALID CUSTOMER NUMBER   - 102: INVALID TELEPROCESSING TYPE   - 103: INVALID COMPANY CODE   - 104: INVALID INPUT/OUTPUT CODE   - 105: ACCOUNT SUSPENDED DUE TO NON-PAYMENT. CALL 800-685-6000 FOR RESOLUTION   - 1F1: LINE ONE DUPLICATE LINES   - 1F2: LINE ONE UNACCEPTABLE FOREIGN BUREAU LINE   - 1F3: LINE ONE INVALID LINE MNEMONIC   - 1F4: LINE ONE LONGER THAN 80 BYTES   Error codes used in the segment’s name portion:   - 201: INVALID LAST NAME   - 202: INVALID FIRST NAME   - 203: INVALID MIDDLE NAME   - 204: INVALID SUFFIX   - 205: INVALID SPOUSE NAME   - 2F1: LINE TWO DUPLICATE LINES   - 2F2: LINE TWO UNACCEPTABLE FOREIGN BUREAU LINE   - 2F3: LINE TWO INVALID LINE MNEMONIC   - 2F4: LINE TWO LONGER THAN 80 BYTES   Inquiry Search Information Error Codes:   - 031: INVALID PHONE NUMBER   - 401: INVALID SUBJECT SOCIAL SECURITY NUMBER   - 403: INVALID SUBJECT AGE   - 404: INVALID SUBJECT SEX   - 405: INVALID SPOUSE BIRTH DATE   - 406: INVALID SPOUSE SOCIAL SECURITY NUMBER   - 407: INVALID NUMBER OF DEPENDENTS   - 408: INVALID MARITAL STATUS   - 4F1: LINE FOUR DUPLICATE LINES   - 4F2: LINE FOUR UNACCEPTABLE FOREIGN BUREAU LINE   - 4F3: LINE FOUR INVALID LINE MNEMONIC   - 4F4: LINE FOUR LONGER THAN 80 BYTES   - 022: MAXIMUM NUMBER OF “AD” SEGMENTS EXCEEDED   - 025: AD SEGMENT DOES NOT FOLLOW IDNT SEGMENT       The codes to follow refer to the first AD Segment:   - 301: INVALID STREET NUMBER   - 302: INVALID STREET NAME   - 303: INVALID STREET TYPE   - 304: INVALID CITY NAME   - 305: INVALID STATE CODE   - 306: INVALID ZIP CODE   - 307: INVALID FILE SINCE   - 308: INVALID R-O-B CODE   - 3F1: LINE THREE DUPLICATE LINES   - 3F2: LINE THREE UNACCEPTABLE FOREIGN BUREAU LINE   - 3F3: LINE THREE INVALID LINE MNEMONIC   - 3F4: LINE THREE LONGER THAN 80 BYTES   These next codes refer to the second AD Segment:   - 501: INVALID FORMER ADDRESS STREET NUMBER   - 503: INVALID FORMER ADDRESS STREET TYPE   - 504: INVALID FORMER ADDRESS CITY NAME   - 505: INVALID FORMER ADDRESS STATE CODE   - 506: INVALID FORMER ADDRESS ZIP CODE   - 507: INVALID FORMER ADDRESS DATE SINCE   - 508: INVALID FORMER ADDRESS R-O-B CODE   - 5F1: LINE FIVE DUPLICATE LINES   - 5F2: LINE FIVE UNACCEPTABLE FOREIGN BUREAU LINE   - 5F3: LINE FIVE INVALID LINE MNEMONIC   - 5F4: LINE FIVE LONGER THAN 80 BYTES   - 6F1: LINE SIX DUPLICATE LINES   - 6F2: LINE SIX UNACCEPTABLE FOREIGN BUREAU LINE   - 6F3: LINE SIX INVALID LINE MNEMONIC   - 6F4: LINE SIX LONGER THAN 80 BYTES      JA Segment Error Conditions:   - 032: MORE THAN ONE JA SEGMENT WAS FOUND     ES Segment Error Conditions:   - 023: MORE THAN ONE ES SEGMENT ENCOUNTERED   - 024: ES SEGMENT DOES NOT FOLLOW AD SEGMENT   - 030: EMPLOYER NAME IS LONGER THAN 35 BYTES     EU Segment Error Conditions:   - 03B: CUSTOMER NUMBER IS EQUAL TO ‘IG’, ‘IL’, ‘IZ’ AND ‘ZB’ AND A PERMISSIBLE PURPOSE CODE IS NOT PRESENT   - 03C: TEXT OR PERMISSIBLE PURPOSE CODE NOT ON “EU” SEG   - 03D: MORE THAN ONE “EU” SEGMENT IS PRESENT ON IDNT   - 03E: CUSTOMER NUMBER IS NOT EQUAL TO A “ZB” AND “EU” IS PRESENT   - 0E0: \\*\\* END USER NOT IDENTIFIED – CONTACT 1-800-685-5000 FOR INFORMATION \\*\\*   - 0EF: PERMISSIBLE PURPOSE CODE IS REQUIRED FOR THIS PRODUCT   - 0F0: INVALID FCRA PERMISSIBLE PURPOSE OR GLB EXCEPTION FOR PRODUCT REQUESTED   - 0F1: PRODUCT NOT AVAILABLE TO INSURANCE INDUSTRY   - 602: LINE 6 FIELD 2 PROBLEM (DIAL SEGMENT = LINE 1)   - 702: INCORRECT PERMISSIBLE PURPOSE CODE         PC Segment Error Conditions:   - 0E2: INVALID PC CODE   - 0E3: MULTIPLE PC CODES NOT ALLOWED   - 0E4: ZIP CODE IS A REQUIRED FIELD   - 0E5: PC SEGMENT REQUIRED WITH PI   - 0E6: ONLY ONE PC SEGMENT ALLOWED   - 0E9: MAXIMUM ALLOWANCE OF PC CODES EXCEEDED   - 0EA: RISKWISE AUTHORIZATION REQUIRED – CONTACT YOUR SALES REP   - 0EB: FRAUD ADVISOR NOT AVAILABLE – CONTACT YOUR SALES REP   - 0EC: ID ADVISOR NOT AVAILABLE – CONTACT YOUR SALES REP   - 0ED: ID ADVISOR PLUS NOT AVAILABLE – CONTACT YOUR SALES REP   - 0EE: MARKETMAX NOT AVAILABLE – CONTACT YOUR SALES REP      PI Segment Error Conditions:   - 0E5: PC SEGMENT REQUIRED WITH PI   - 0E7: ONLY ONE PI SEGMENT ALLOWED   - 0E8: INVALID OR INCOMPLETE DATA ON PI SEGMENT       Processing Error Codes (Processing Error Codes apply to the Fixed Inquiry Format.):   - 002: NO RECORD FOUND - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 003: ERROR IN MASTER RECORD - CONTACT EQUIFAX AUTOMATED DELIVERY SYSTEMS   - 006: SPOUSE NAME REQUIRED FOR JOINT FILE ACCESS   - 008: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 009: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 00A: YOUR TRANSACTION WAS NOT COMPLETED - ERROR HAS OCCURRED IN SEARCHING FILE   - 014: RE-ENTER YOUR ENTIRE TRANSACTION - FILE HAS BEEN CHANGED SINCE YOU INQUIRED   - 015: CONTACT EQUIFAX - AUTOMATED DELIVERY SYSTEMS   - 01B: YOUR NM LINE IS INVALID   - 01C: YOUR ADDRESS LINE IS INVALID   - 01D: CURRENT AND FORMER ADDRESS BOTH OUT OF AREA   - 021: ERROR IN PREPARING YOUR FORM - RE-ORDER FORM - BILLING AND MAINTENANCE IS OK   - 02B: CA - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02C: FA - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02D: F2 - CITY OR STATE MISSPELLED OR NOT IN ACROPAC SYSTEM   - 02E: THIS AREA OF RECORDS TEMPORARILY UNAVAILABLE - PLEASE TRY LATER   - 03A: NO ADDITIONAL BILLING ENTRIES ALLOWED WITH BILL - NO   - 03E: YOUR REPLY IS INVALID SINCE IT HAS ALREADY BEEN ENTERED ON THIS TRANSACTION   - 040: NOT AUTHORIZED TO RECEIVE THIS PRODUCT   - 045: PROGRAM ERROR - PRINT TOTAL TRANSACTION AND NOTIFY AUTOMATION DIVISION (CONTACT BUREAU)   - 046: ADDRESS - CITY OR STATE IS MISSPELLED OR NOT IN ACROPAC SYSTEM   - 04A: INVALID SECURITY CODE - USE YOUR CORRECT CODE   - 06E: INVALID REQUEST   - 076: CONTACT BUREAU SUPERVISOR - FILE EXCEEDS MAXIMUM LENGTH   - 077: CANCELED CUSTOMER NUMBER - CONTACT EQUIFAX SALES DEPARTMENT   - 078: SECURITY VIOLATION - UNAUTHORIZED TRANSACTION TYPE   - 079: UNABLE TO BUILD SUMMARY OUTPUT FOR THIS RECORD   - 07A: UNABLE TO BUILD TOTALVIEW FULL-FILE FIXED OUTPUT FOR THIS RECORD   - 07B: UNABLE TO BUILD PRINT IMAGE OUTPUT FOR THIS RECORD   - 07C: INSUFFICIENT INFORMATION FOR FILE SEARCH – ADDITIONAL DATA IS NEEDED   - 0A3: SOCIAL SECURITY NUMBER IS REQUIRED TO ACCESS PUERTO RICO FILES   - 0A4: NO RECORD SUBJECT (JOINT FILE ACCESS) - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 0A5: NO RECORD SPOUSE (JOINT FILE ACCESS) - CHECK INPUT FOR ACCURACY, IF SOCIAL AVAILABLE TRY DTEC   - 0A7: COMBINED FILE IS TOO LARGE FOR PROCESSING. PLEASE RE-SUBMIT USING ONLY CANADIAN ADDRESS   - 0A8: NO CANADIAN ADDRESS IN THE INQUIRY.   - 0A9: CANADIAN FILE NOT AVAILABLE IN ACROFILE PLUS FORMAT   - 0C6: SOCIAL SECURITY NUMBER REQUIRED ON INPUT WHEN USING MILITARY ADDRESS   - 0E1: VERMONT FILES BLOCKED - CONTACT 1-800-685-5000 FOR REQUIRED CERTIFICATION   - 0F0: INVALID FCRA PERMISSIBLE PURPOSE OR GLB EXCEPTION FOR PRODUCT REQUESTED   - 0F9: CURRENT ADDRESS ON FILE IS MINNESOTA - FILE BLOCKED   - 4F5: INVALID ACCOUNT NUMBER   MERR: Model Data Response Error  NARRATIVE CODES:   - M00010: Model Segment Invalid   - M20010: Invalid Model Segment Input Data.   - M20020: Message will be one of the following five:   - M20030:   - M20040: Invalid Alpha-nn   - M20050: Invalid Numeric-nn   - M20060: Invalid Alpha/Numeric-nn   - M20070: Invalid Date-nn   - M20080: Invalid Length-nn   - M20100: Where “nn” and the 4th and 5th digits of the error number indicate which “MD” field that is error   - M20400: Member Number is not Authorized for Model Delivery   - M20500: “MD” Segment contains Invalid Number of Input Fields   - M20600: Error in Report ID not using a prescreen   - M20700: Error in Report ID multi model Not G,P, or DDT09   - M20800: Error conflicting report Ids in the MAT table set up ")
      @NotNull

    public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ErrorResponseInner errorType(ErrorTypeEnum errorType) {
    this.errorType = errorType;
    return this;
  }

  /**
   * Error type
   * @return errorType
  **/
  @ApiModelProperty(required = true, value = "Error type")
      @NotNull

    public ErrorTypeEnum getErrorType() {
    return errorType;
  }

  public void setErrorType(ErrorTypeEnum errorType) {
    this.errorType = errorType;
  }

  public ErrorResponseInner message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Error description
   * @return message
  **/
  @ApiModelProperty(value = "Error description")
  
    public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseInner errorResponseInner = (ErrorResponseInner) o;
    return Objects.equals(this.code, errorResponseInner.code) &&
        Objects.equals(this.errorType, errorResponseInner.errorType) &&
        Objects.equals(this.message, errorResponseInner.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, errorType, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseInner {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    errorType: ").append(toIndentedString(errorType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
