package com.b4nkd.creditscore.equifax.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * NarrativeCodesInner
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-08T10:55:31.099545300Z[Europe/London]")


public class NarrativeCodesInner   {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("description")
  private String description = null;

  public NarrativeCodesInner code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Code value
   * @return code
  **/
  @ApiModelProperty(value = "Code value")
  
    public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public NarrativeCodesInner description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Narrative codes and descriptions:   - AA: CONSUMER SAYS MERCHANDISE OR SERVICE UNSATISFACTORY   - AB: CONSUMER SAYS ACCOUNT PAID/BEING PAID BY INSURANCE   - AC: CONSUMER SAYS ACCT IS RESPONSIBILITY OF SEPARATED OR DIVORCED SPOUSE   - AE: CONSUMER SAYS ACCT. INVOLVED IN BUSINESS VENTURE HELD PERSONALLY LIAB   - AF: CONSUMER SAYS ACCOUNT INVOLVES LEASE AGREEMENT DISPUTE   - AG: CONSUMER DISPUTES ACCOUNT - LITIGATION PENDING   - AH: CONSUMER SAYS ACCOUNT SLOW DUE TO BILLING DISPUTE WITH CREDITOR   - AI: CONSUMER SAYS ACCOUNT SLOW DUE TO EMPLOYMENT ISSUES   - AJ: CONSUMER SAYS ACCOUNT SLOW DUE TO MEDICAL EXPENSES/ILLNESS   - AL: CONSUMER SAYS WARRANTY DISPUTE   - AM: VOLUNTARY SURRENDER; THERE MAY BE A BALANCE DUE   - AN: INVOLUNTARY REPOSSESSION   - AO: AUTO   - AP: COMMERCIAL ACCOUNT   - AQ: HOUSEHOLD GOODS   - AR: HOME LOAN   - AS: HOME IMPROVEMENT LOAN   - AT: CHECKING ACCOUNT LOAN PLAN   - AU: PERSONAL LOAN   - AV: CHARGE   - AW: SECURED BY HOUSEHOLD GOODS   - AX: PAID BY DEALER   - AY: VOLUNTARILY SURRENDERED – THEN REDEEMED OR REINSTATED   - AZ: AMOUNT IN H/C COLUMN IS CREDIT LIMIT   - BB: CONSUMER DISPUTES THIS ACCOUNT INFORMATION   - BC: ACCOUNT TRANSFERRED OR SOLD   - BD: PAID - CREDIT LINE CLOSED   - BE: CREDIT LINE CLOSED   - BG: CLAIM FILED WITH GOVERNMENT   - BH: DISPUTE - RESOLUTION PENDING   - BK: REDEEMED OR REINSTATED REPOSSESSION   - BL: CONSUMER SAYS ACCOUNT SLOW DUE TO DOMESTIC PROBLEMS   - BM: CONSUMER SAYS PAID ON NOTIFICATION - NO PRIOR KNOWLEDGE OF BALANCE DUE   - BN: CONSUMER SAYS CO-SIGNED ACCOUNT - NOT AWARE OF DELINQUENCY   - BO: CONSUMER SAYS NO STATEMENT RECEIVED DUE TO ADDRESS CHANGE   - BP: CONSUMER SAYS THIS ACCOUNT SPOUSE’S RESPONSIBILITY   - BQ: PAID CHARGE OFF   - BR: FORECLOSURE PROCESS STARTED   - BS: PAID OR BEING PAID BY GOVERNMENT GUARANTOR   - BT: LEASE   - BU: STUDENT LOAN   - BV: CONSUMER DISPUTE FOLLOWING RESOLUTION   - BW: INCLUDED IN BANKRUPTCY   - BX: PAYMENTS MANAGED BY FINANCIAL COUNSELING PROGRAM   - BY: COLLECTION AGENCY ACCOUNT - STATUS UNKNOWN   - BZ: ACCOUNT PAID FOR LESS THAN FULL BALANCE   - CA: CHARGE OFF - MAKING PAYMENTS   - CB: CHARGED OFF - CHECK PRESENTED WAS UNCOLLECTIBLE   - CD: CUSTOMER HAS NOW LOCATED CONSUMER   - CE: REFINANCED   - CF: CLOSED ACCOUNT   - CG: ACCOUNT CLOSED - REASON UNKNOWN   - CH: ACCOUNT PAID AFTER FORECLOSURE STARTED   - CI: INSURANCE CLAIM PENDING   - CJ: CUSTOMER UNABLE TO LOCATE CONSUMER   - CK: DEBIT CARD   - CL: PAID OR BEING PAID BY CO-SIGNER OR GUARANTOR   - CM: ACCOUNT ASSUMED BY ANOTHER PARTY   - CN: PAYING UNDER A PARTIAL PAYMENT AGREEMENT   - CP: CONSUMER SAYS PERSONAL BANKRUPTCY FILED DUE TO BUSINESS FAILURE   - CQ: PLTFF VERIFIED JUDGMENT PAID/SATISFACTION NOT RECORDED WITH COURT   - CS: SECURED CREDIT LINE   - CT: VOLUNTARY   - CU: INVOLUNTARY   - CV: LINE OF CREDIT   - CW: ACCOUNT CLOSED BY CREDIT GRANTOR   - CX: PAYMENT IS PAYROLL DEDUCTIBLE   - CY: ACCOUNT CHARGED TO PROFIT AND LOSS   - CZ: COLLECTION ACCOUNT   - DA: ACCOUNT CLOSED BY CONSUMER   - DB: CHARGED OFF ACCOUNT   - DC: CONSUMER SAYS ACCOUNT NOT PAID PROMPTLY - INSURANCE CLAIM DELAYED   - DD: BALANCE IS DEFICIENCY AMOUNT   - DE: CONSUMER SAYS ACCOUNT PAID IN FULL   - DG: TITLE 1 LOAN   - DH: BALANCE NOT PAID BY INSURANCE   - DI: BALANCE PAID OR BEING PAID BY INSURANCE COMPANY   - DJ: FORECLOSURE   - DK: PAID OR BEING PAID BY GARNISHMENT   - DL: CONSUMER RECALLED TO ACTIVE MILITARY DUTY   - DM: FORFEIT OF DEED IN LIEU OF FORECLOSURE   - DN: BROKEN LEASE AGREEMENT   - DO: BANKRUPTCY CHAPTER 13   - DP: CONVERSION LOSS PAID BY INSURANCE   - DQ: STUDENT LOAN - PAYMENT DEFERRED   - DS: SINGLE PAYMENT LOAN   - DT: AMORTIZED MORTGAGE   - DU: SHERIFF SALE   - DV: AMOUNT IN HIGH CREDIT INCLUDES FINANCE CHARGE   - DW: RETURN MAIL   - DX: BALANCE OWING - AMOUNT NOT REPORTED   - EA: PAID OR MAKING PAYMENTS - NOT ACCORDING TO TERMS OF AGREEMENT   - EB: LEASE - EARLY TERMINATION BY DEFAULT   - EC: HOME EQUITY   - ED: MAKING PAYMENT - FORECLOSURE WAS INITIATED   - EE: SECURED   - EF: REAL ESTATE MORTGAGE   - EG: GUARANTEED STUDENT LOAN   - EH: NATIONAL DIRECT STUDENT LOAN   - EI: CONSUMER DISPUTES ACCOUNT - LITIGATION FILED BY CREDITOR PENDING   - EJ: CONSUMER DISPUTES ACCOUNT - LITIGATION FILED BY CONSUMER PENDING   - EK: CHILD/FAMILY SUPPORT OBLIGATION   - EL: DEFENDANT VERIFIED ITEM PD/SATISFACTION NOT RECORDED WITH COURT   - EM: VOLUNTARY RETURN OF PURCHASE   - EP: FIXED RATE   - EQ: VARIABLE/ADJUSTABLE RATE   - ER: PAID COLLECTION   - ES: CHARGED BACK TO DEALER   - ET: PAID REPOSSESSION   - EU: SEE CONSUMER STATEMENT   - EV: BANKRUPTCY CHAPTER 11   - EX: UNSECURED   - EY: BUSINESS ACCOUNT - PERSONAL GUARANTEE   - EZ: HAS CO-SIGNER   - FA: CLOSED OR PAID ACCOUNT/ZERO BALANCE   - FB: INCLUDED IN ORDERLY PAYMENT DEBT   - FC: CREDIT LINE SUSPENDED   - FD: DEFAULTED STUDENT LOAN   - FE: CREDIT CARD   - FF: CONSUMER SAYS ACCOUNT NOT HIS/HERS   - FG: CONSUMER SAYS ACCOUNT NEVER LATE   - FH: CONSUMER SAYS THIS PUBLIC RECORD NOT HIS/HERS   - FL: CONSUMER SAYS THIS PUBLIC RECORD FILED IN ERROR   - FM: CONSUMER SAYS THIS PUBLIC RECORD ITEM SATISFIED OR RELEASED   - FO: CONSUMER SAYS BANKRUPTCY DISCHARGED   - FP: CONSUMER SAYS BANKRUPTCY DISMISSED   - FQ: CONSUMER SAYS CURRENT RATE/STATUS INCORRECT   - FR: MAKING PAYMENTS   - FS: ANNUAL PAYMENT   - FU: CHARGED OFF CHECKING ACCOUNT   - FV: PLTFF VERIFIED LIEN PD/RELEASE NOT RECORDED WITH COURT   - FW: CONSUMER DISPUTES – REINVESTIGATION IN PROGRESS   - FX: ACCOUNT LISTED AS PUBLIC RECORD   - FZ: ACCOUNT REINSTATED WITH LENDER   - GA: PAID BY COLLATERAL   - GB: ACCOUNT BEING PAID THROUGH WEP   - GC: ACCOUNT BEING PAID THROUGH FINANCIAL COUNSELING PLAN   - GD: ACCOUNT PAID THROUGH FINANCIAL COUNSELING PLAN   - GE: CONSUMER DISPUTES THIS ITEM   - GF: REAFFIRMATION OF DEBT   - GH: PLAINTIFF/COUNSEL VERIFIED JUDGEMENT PAID   - GI: UTILITY   - GJ: STUDENT LOAN ASSIGNED TO GOVERNMENT   - GK: AFFECTED BY NATURAL DISASTER   - GL: FIRST PAYMENT NEVER RECEIVED   - GM: ACCOUNT ACQUIRED BY FDIC/NCUA   - GN: GOVERNMENT DEBT   - GO: DEBT CONSOLIDATION   - GP: MANUFACTURED HOUSING   - GQ: RECREATIONAL MERCHANDISE   - GR: SECURED CREDIT CARD   - GS: MEDICAL   - HF: ACCOUNT CLOSED BY CONSUMER   - HL: 100% PAYMENT TO CREDITORS FILING CLAIMS   - HO: RETURNED CHECK   - HP: FHA MORTGAGE   - HQ: VA MORTGAGE   - HR: CONVENTIONAL MORTGAGE   - HS: SECOND MORTGAGE   - HT: AGRICULTURAL   - HU: COMMERCIAL MORTGAGE-INDIVIDUAL LIABLE, COMPANY IS GUARANTOR   - HV: DEPOSIT RELATED   - HW: CHILD/FAMILY SUPPORT   - HX: TRANSFERRED TO RECOVERY   - IB: LEASE - FULL TERMINATION   - IC: LEASE - EARLY TERMINATION   - ID: STATUS PENDING   - IE: FANNIE MAE ACCOUNT   - IF: FREDDIE MAC ACCOUNT   - IG: PREPAID LEASE   - IH: CONSUMER PAYS BALANCE IN FULL EACH MONTH   - II: PRINCIPAL DEFERRED/INTEREST PAYMENT ONLY   - IJ: PAYMENT DEFERRED   - IK: BANKRUPTCY VOLUNTARILY WITHDRAWN   - IL: BANKRUPTCY CHAPTER 7   - IM: BANKRUPTCY CHAPTER 12   - IN: REAFFIRMATION OF DEBT RESCINDED   - IP: CONSUMER DISPUTES THIS ACCOUNT INFORMATION   - IQ: CONSUMER DISPUTES AFTER RESOLUTION   - IR: ACCOUNT CLOSED AT CONSUMER’S REQUEST   - IT: ACCOUNT ACQUIRED FROM ANOTHER LENDER   - IZ: AMOUNT IN HIGH CREDIT IS ORIGINAL CHARGE-OFF AMOUNT   - JA: ELECTION OF REMEDY   - JD: CONSUMER DECEASED   - JE: ADJUSTMENT PENDING   - JF: INACTIVE ACCOUNT   - JG: DOLLAR AMOUNT IN EXCESS OF $1 BILLION   - JH: PERSONAL RECEIVERSHIP – REPAYMENT MANAGED BY COURT TRUSTEE   - JI: GUARANTEED/INSURED   - JJ: TIME SHARE LOAN   - JK: 120 DAYS PAST DUE   - JL: 150 DAYS PAST DUE   - JM: 180 DAYS OR MORE PAST DUE   - JN: PARTIALLY SECURED   - JO: NOTE LOAN   - JP: RENTAL AGREEMENT   - JQ: AUTO LEASE   - JR: TELECOMMUNICATIONS/CELLULAR   - JS: UNSECURED GOVERNMENT LOAN   - JT: SECURED GOVERNMENT LOAN   - JU: HOME EQUITY LINE OF CREDIT   - JV: ATTORNEY FEES   - JW: CONSTRUCTION LOAN   - JX: FLEXIBLE SPENDING CREDIT CARD   - JY: COMBINED CREDIT PLAN   - JZ: DEBT BUYER ACCOUNT   - KA: INSTALLMENT SALES CONTRACT   - KB: BANKRUPTCY PETITION   - KC: BANKRUPTCY DISCHARGED   - KD: BANKRUPTCY COMPLETED   - KE: LEASE ASSUMPTION   - KF: ACCOUNT PREVIOUSLY IN DISPUTE – NOW RESOLVED BY DATA FURNISHER   - KG: CHAPTER 7 BANKRUPTCY DISMISSED   - KH: CHAPTER 11 BANKRUPTCY DISMISSED   - KI: CHAPTER 12 BANKRUPTCY DISMISSED   - KJ: CHAPTER 13 BANKRUPTCY DISMISSED   - KK: CHAPTER 7 BANKRUPTCY WITHDRAWN   - KL: CHAPTER 11 BANKRUPTCY WITHDRAWN   - KM: CHAPTER 12 BANKRUPTCY WITHDRAWN   - KN: CHAPTER 13 BANKRUPTCY WITHDRAWN   - KO: BANKRUPCTY – UNDESIGNATED CHAPTER   - KP: ACCOUNT CLOSED DUE TO INACTIVITY   - KQ: CREDIT LINE NO LONGER AVAILABLE - IN REPAYMENT PHASE   - KR: CREDIT LINE REDUCED DUE TO COLLATERAL DEPRECIATION   - KS: CREDIT LINE SUSPENDED DUE TO COLLATERAL DEPRECIATION   - KT: COLLATERAL RELEASED BY CREDITOR/BALANCE OWING   - KU: LOAN MODIFIED UNDER A FEDERAL GOVERNMENT PLAN   - KV: LOAN MODIFIED   - KW: ACCOUNT IN FORBEARANCE   - KZ: ACCOUNT PAID IN FULL; WAS A VOLUNTARY SURRENDER   - LB: HOMEOWNERS ASSOCIATION (HOA) 
   * @return description
  **/
  @ApiModelProperty(value = "Narrative codes and descriptions:   - AA: CONSUMER SAYS MERCHANDISE OR SERVICE UNSATISFACTORY   - AB: CONSUMER SAYS ACCOUNT PAID/BEING PAID BY INSURANCE   - AC: CONSUMER SAYS ACCT IS RESPONSIBILITY OF SEPARATED OR DIVORCED SPOUSE   - AE: CONSUMER SAYS ACCT. INVOLVED IN BUSINESS VENTURE HELD PERSONALLY LIAB   - AF: CONSUMER SAYS ACCOUNT INVOLVES LEASE AGREEMENT DISPUTE   - AG: CONSUMER DISPUTES ACCOUNT - LITIGATION PENDING   - AH: CONSUMER SAYS ACCOUNT SLOW DUE TO BILLING DISPUTE WITH CREDITOR   - AI: CONSUMER SAYS ACCOUNT SLOW DUE TO EMPLOYMENT ISSUES   - AJ: CONSUMER SAYS ACCOUNT SLOW DUE TO MEDICAL EXPENSES/ILLNESS   - AL: CONSUMER SAYS WARRANTY DISPUTE   - AM: VOLUNTARY SURRENDER; THERE MAY BE A BALANCE DUE   - AN: INVOLUNTARY REPOSSESSION   - AO: AUTO   - AP: COMMERCIAL ACCOUNT   - AQ: HOUSEHOLD GOODS   - AR: HOME LOAN   - AS: HOME IMPROVEMENT LOAN   - AT: CHECKING ACCOUNT LOAN PLAN   - AU: PERSONAL LOAN   - AV: CHARGE   - AW: SECURED BY HOUSEHOLD GOODS   - AX: PAID BY DEALER   - AY: VOLUNTARILY SURRENDERED – THEN REDEEMED OR REINSTATED   - AZ: AMOUNT IN H/C COLUMN IS CREDIT LIMIT   - BB: CONSUMER DISPUTES THIS ACCOUNT INFORMATION   - BC: ACCOUNT TRANSFERRED OR SOLD   - BD: PAID - CREDIT LINE CLOSED   - BE: CREDIT LINE CLOSED   - BG: CLAIM FILED WITH GOVERNMENT   - BH: DISPUTE - RESOLUTION PENDING   - BK: REDEEMED OR REINSTATED REPOSSESSION   - BL: CONSUMER SAYS ACCOUNT SLOW DUE TO DOMESTIC PROBLEMS   - BM: CONSUMER SAYS PAID ON NOTIFICATION - NO PRIOR KNOWLEDGE OF BALANCE DUE   - BN: CONSUMER SAYS CO-SIGNED ACCOUNT - NOT AWARE OF DELINQUENCY   - BO: CONSUMER SAYS NO STATEMENT RECEIVED DUE TO ADDRESS CHANGE   - BP: CONSUMER SAYS THIS ACCOUNT SPOUSE’S RESPONSIBILITY   - BQ: PAID CHARGE OFF   - BR: FORECLOSURE PROCESS STARTED   - BS: PAID OR BEING PAID BY GOVERNMENT GUARANTOR   - BT: LEASE   - BU: STUDENT LOAN   - BV: CONSUMER DISPUTE FOLLOWING RESOLUTION   - BW: INCLUDED IN BANKRUPTCY   - BX: PAYMENTS MANAGED BY FINANCIAL COUNSELING PROGRAM   - BY: COLLECTION AGENCY ACCOUNT - STATUS UNKNOWN   - BZ: ACCOUNT PAID FOR LESS THAN FULL BALANCE   - CA: CHARGE OFF - MAKING PAYMENTS   - CB: CHARGED OFF - CHECK PRESENTED WAS UNCOLLECTIBLE   - CD: CUSTOMER HAS NOW LOCATED CONSUMER   - CE: REFINANCED   - CF: CLOSED ACCOUNT   - CG: ACCOUNT CLOSED - REASON UNKNOWN   - CH: ACCOUNT PAID AFTER FORECLOSURE STARTED   - CI: INSURANCE CLAIM PENDING   - CJ: CUSTOMER UNABLE TO LOCATE CONSUMER   - CK: DEBIT CARD   - CL: PAID OR BEING PAID BY CO-SIGNER OR GUARANTOR   - CM: ACCOUNT ASSUMED BY ANOTHER PARTY   - CN: PAYING UNDER A PARTIAL PAYMENT AGREEMENT   - CP: CONSUMER SAYS PERSONAL BANKRUPTCY FILED DUE TO BUSINESS FAILURE   - CQ: PLTFF VERIFIED JUDGMENT PAID/SATISFACTION NOT RECORDED WITH COURT   - CS: SECURED CREDIT LINE   - CT: VOLUNTARY   - CU: INVOLUNTARY   - CV: LINE OF CREDIT   - CW: ACCOUNT CLOSED BY CREDIT GRANTOR   - CX: PAYMENT IS PAYROLL DEDUCTIBLE   - CY: ACCOUNT CHARGED TO PROFIT AND LOSS   - CZ: COLLECTION ACCOUNT   - DA: ACCOUNT CLOSED BY CONSUMER   - DB: CHARGED OFF ACCOUNT   - DC: CONSUMER SAYS ACCOUNT NOT PAID PROMPTLY - INSURANCE CLAIM DELAYED   - DD: BALANCE IS DEFICIENCY AMOUNT   - DE: CONSUMER SAYS ACCOUNT PAID IN FULL   - DG: TITLE 1 LOAN   - DH: BALANCE NOT PAID BY INSURANCE   - DI: BALANCE PAID OR BEING PAID BY INSURANCE COMPANY   - DJ: FORECLOSURE   - DK: PAID OR BEING PAID BY GARNISHMENT   - DL: CONSUMER RECALLED TO ACTIVE MILITARY DUTY   - DM: FORFEIT OF DEED IN LIEU OF FORECLOSURE   - DN: BROKEN LEASE AGREEMENT   - DO: BANKRUPTCY CHAPTER 13   - DP: CONVERSION LOSS PAID BY INSURANCE   - DQ: STUDENT LOAN - PAYMENT DEFERRED   - DS: SINGLE PAYMENT LOAN   - DT: AMORTIZED MORTGAGE   - DU: SHERIFF SALE   - DV: AMOUNT IN HIGH CREDIT INCLUDES FINANCE CHARGE   - DW: RETURN MAIL   - DX: BALANCE OWING - AMOUNT NOT REPORTED   - EA: PAID OR MAKING PAYMENTS - NOT ACCORDING TO TERMS OF AGREEMENT   - EB: LEASE - EARLY TERMINATION BY DEFAULT   - EC: HOME EQUITY   - ED: MAKING PAYMENT - FORECLOSURE WAS INITIATED   - EE: SECURED   - EF: REAL ESTATE MORTGAGE   - EG: GUARANTEED STUDENT LOAN   - EH: NATIONAL DIRECT STUDENT LOAN   - EI: CONSUMER DISPUTES ACCOUNT - LITIGATION FILED BY CREDITOR PENDING   - EJ: CONSUMER DISPUTES ACCOUNT - LITIGATION FILED BY CONSUMER PENDING   - EK: CHILD/FAMILY SUPPORT OBLIGATION   - EL: DEFENDANT VERIFIED ITEM PD/SATISFACTION NOT RECORDED WITH COURT   - EM: VOLUNTARY RETURN OF PURCHASE   - EP: FIXED RATE   - EQ: VARIABLE/ADJUSTABLE RATE   - ER: PAID COLLECTION   - ES: CHARGED BACK TO DEALER   - ET: PAID REPOSSESSION   - EU: SEE CONSUMER STATEMENT   - EV: BANKRUPTCY CHAPTER 11   - EX: UNSECURED   - EY: BUSINESS ACCOUNT - PERSONAL GUARANTEE   - EZ: HAS CO-SIGNER   - FA: CLOSED OR PAID ACCOUNT/ZERO BALANCE   - FB: INCLUDED IN ORDERLY PAYMENT DEBT   - FC: CREDIT LINE SUSPENDED   - FD: DEFAULTED STUDENT LOAN   - FE: CREDIT CARD   - FF: CONSUMER SAYS ACCOUNT NOT HIS/HERS   - FG: CONSUMER SAYS ACCOUNT NEVER LATE   - FH: CONSUMER SAYS THIS PUBLIC RECORD NOT HIS/HERS   - FL: CONSUMER SAYS THIS PUBLIC RECORD FILED IN ERROR   - FM: CONSUMER SAYS THIS PUBLIC RECORD ITEM SATISFIED OR RELEASED   - FO: CONSUMER SAYS BANKRUPTCY DISCHARGED   - FP: CONSUMER SAYS BANKRUPTCY DISMISSED   - FQ: CONSUMER SAYS CURRENT RATE/STATUS INCORRECT   - FR: MAKING PAYMENTS   - FS: ANNUAL PAYMENT   - FU: CHARGED OFF CHECKING ACCOUNT   - FV: PLTFF VERIFIED LIEN PD/RELEASE NOT RECORDED WITH COURT   - FW: CONSUMER DISPUTES – REINVESTIGATION IN PROGRESS   - FX: ACCOUNT LISTED AS PUBLIC RECORD   - FZ: ACCOUNT REINSTATED WITH LENDER   - GA: PAID BY COLLATERAL   - GB: ACCOUNT BEING PAID THROUGH WEP   - GC: ACCOUNT BEING PAID THROUGH FINANCIAL COUNSELING PLAN   - GD: ACCOUNT PAID THROUGH FINANCIAL COUNSELING PLAN   - GE: CONSUMER DISPUTES THIS ITEM   - GF: REAFFIRMATION OF DEBT   - GH: PLAINTIFF/COUNSEL VERIFIED JUDGEMENT PAID   - GI: UTILITY   - GJ: STUDENT LOAN ASSIGNED TO GOVERNMENT   - GK: AFFECTED BY NATURAL DISASTER   - GL: FIRST PAYMENT NEVER RECEIVED   - GM: ACCOUNT ACQUIRED BY FDIC/NCUA   - GN: GOVERNMENT DEBT   - GO: DEBT CONSOLIDATION   - GP: MANUFACTURED HOUSING   - GQ: RECREATIONAL MERCHANDISE   - GR: SECURED CREDIT CARD   - GS: MEDICAL   - HF: ACCOUNT CLOSED BY CONSUMER   - HL: 100% PAYMENT TO CREDITORS FILING CLAIMS   - HO: RETURNED CHECK   - HP: FHA MORTGAGE   - HQ: VA MORTGAGE   - HR: CONVENTIONAL MORTGAGE   - HS: SECOND MORTGAGE   - HT: AGRICULTURAL   - HU: COMMERCIAL MORTGAGE-INDIVIDUAL LIABLE, COMPANY IS GUARANTOR   - HV: DEPOSIT RELATED   - HW: CHILD/FAMILY SUPPORT   - HX: TRANSFERRED TO RECOVERY   - IB: LEASE - FULL TERMINATION   - IC: LEASE - EARLY TERMINATION   - ID: STATUS PENDING   - IE: FANNIE MAE ACCOUNT   - IF: FREDDIE MAC ACCOUNT   - IG: PREPAID LEASE   - IH: CONSUMER PAYS BALANCE IN FULL EACH MONTH   - II: PRINCIPAL DEFERRED/INTEREST PAYMENT ONLY   - IJ: PAYMENT DEFERRED   - IK: BANKRUPTCY VOLUNTARILY WITHDRAWN   - IL: BANKRUPTCY CHAPTER 7   - IM: BANKRUPTCY CHAPTER 12   - IN: REAFFIRMATION OF DEBT RESCINDED   - IP: CONSUMER DISPUTES THIS ACCOUNT INFORMATION   - IQ: CONSUMER DISPUTES AFTER RESOLUTION   - IR: ACCOUNT CLOSED AT CONSUMER’S REQUEST   - IT: ACCOUNT ACQUIRED FROM ANOTHER LENDER   - IZ: AMOUNT IN HIGH CREDIT IS ORIGINAL CHARGE-OFF AMOUNT   - JA: ELECTION OF REMEDY   - JD: CONSUMER DECEASED   - JE: ADJUSTMENT PENDING   - JF: INACTIVE ACCOUNT   - JG: DOLLAR AMOUNT IN EXCESS OF $1 BILLION   - JH: PERSONAL RECEIVERSHIP – REPAYMENT MANAGED BY COURT TRUSTEE   - JI: GUARANTEED/INSURED   - JJ: TIME SHARE LOAN   - JK: 120 DAYS PAST DUE   - JL: 150 DAYS PAST DUE   - JM: 180 DAYS OR MORE PAST DUE   - JN: PARTIALLY SECURED   - JO: NOTE LOAN   - JP: RENTAL AGREEMENT   - JQ: AUTO LEASE   - JR: TELECOMMUNICATIONS/CELLULAR   - JS: UNSECURED GOVERNMENT LOAN   - JT: SECURED GOVERNMENT LOAN   - JU: HOME EQUITY LINE OF CREDIT   - JV: ATTORNEY FEES   - JW: CONSTRUCTION LOAN   - JX: FLEXIBLE SPENDING CREDIT CARD   - JY: COMBINED CREDIT PLAN   - JZ: DEBT BUYER ACCOUNT   - KA: INSTALLMENT SALES CONTRACT   - KB: BANKRUPTCY PETITION   - KC: BANKRUPTCY DISCHARGED   - KD: BANKRUPTCY COMPLETED   - KE: LEASE ASSUMPTION   - KF: ACCOUNT PREVIOUSLY IN DISPUTE – NOW RESOLVED BY DATA FURNISHER   - KG: CHAPTER 7 BANKRUPTCY DISMISSED   - KH: CHAPTER 11 BANKRUPTCY DISMISSED   - KI: CHAPTER 12 BANKRUPTCY DISMISSED   - KJ: CHAPTER 13 BANKRUPTCY DISMISSED   - KK: CHAPTER 7 BANKRUPTCY WITHDRAWN   - KL: CHAPTER 11 BANKRUPTCY WITHDRAWN   - KM: CHAPTER 12 BANKRUPTCY WITHDRAWN   - KN: CHAPTER 13 BANKRUPTCY WITHDRAWN   - KO: BANKRUPCTY – UNDESIGNATED CHAPTER   - KP: ACCOUNT CLOSED DUE TO INACTIVITY   - KQ: CREDIT LINE NO LONGER AVAILABLE - IN REPAYMENT PHASE   - KR: CREDIT LINE REDUCED DUE TO COLLATERAL DEPRECIATION   - KS: CREDIT LINE SUSPENDED DUE TO COLLATERAL DEPRECIATION   - KT: COLLATERAL RELEASED BY CREDITOR/BALANCE OWING   - KU: LOAN MODIFIED UNDER A FEDERAL GOVERNMENT PLAN   - KV: LOAN MODIFIED   - KW: ACCOUNT IN FORBEARANCE   - KZ: ACCOUNT PAID IN FULL; WAS A VOLUNTARY SURRENDER   - LB: HOMEOWNERS ASSOCIATION (HOA) ")
  
    public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NarrativeCodesInner narrativeCodesInner = (NarrativeCodesInner) o;
    return Objects.equals(this.code, narrativeCodesInner.code) &&
        Objects.equals(this.description, narrativeCodesInner.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NarrativeCodesInner {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
